name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Build with Gradle
        run: ./gradlew build --build-cache

      - name: Infer and publish release with Nyx
        id: nyx
        uses: mooltiverse/nyx-github-action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_VERBOSITY: 'INFO'
        with:
          command: 'publish'
          preset: 'extended'
          releaseLenient: 'true'
          stateFile: '.nyx-state.json'
          changelogPath: 'CHANGELOG.md'
          summaryFile: '.nyx-summary.txt'