name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  infer-release:
    runs-on: ubuntu-latest # Use Linux for the Nyx action
    outputs:
      version: ${{ steps.nyx.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up the cache to store and retrieve the Nyx state
        uses: actions/cache@v3
        with:
          path: |
            .nyx-state.json
          key: $-nyx-state
          restore-keys: $-nyx-state

      - name: Infer release with Nyx
        id: nyx
        uses: mooltiverse/nyx-github-action@main
        env:
          NYX_VERBOSITY: 'INFO'
        with:
          configurationFile: 'build-configuration/.nyx.json'
          command: 'infer'
          stateFile: .nyx-state.json
          changelogPath: CHANGELOG.md

      - name: Echo the output
        run: echo The release version is ${{ steps.nyx.outputs.version }}

  build-and-publish:
    runs-on: macos-13 # Use macOS for the rest of the steps
    needs: infer-release # Wait for the Nyx job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Publish with Gradle
        run: ./gradlew publish -Pversion=$VERSION --build-cache
        env:
          VERSION: ${{ needs.infer-release.outputs.version }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}