name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Infer release with Nyx
        id: nyx
        uses: mooltiverse/nyx-github-action@main
        env:
          NYX_VERBOSITY: 'INFO'
        with:
          releasePrefix: 'v'
          command: 'infer'

      - name: Publish with Gradle
        run: ./gradlew publish -Pversion=${{ steps.nyx.outputs.version }} --build-cache
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}