on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  infer-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.nyx.outputs.version }}
      
    steps:
      - name: "🔎 Preflight: check signing secrets"
        run: |
          test -n "${ORG_GRADLE_PROJECT_signingInMemoryKey}" || { echo "Signing key is EMPTY"; exit 1; }
          test -n "${ORG_GRADLE_PROJECT_signingInMemoryKeyPassword}" || { echo "Signing password is EMPTY"; exit 1; }
          echo "Signing key length: ${#ORG_GRADLE_PROJECT_signingInMemoryKey}"
          echo "OK: secrets present"
        shell: bash
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
